# Generated by Django 5.1.1 on 2024-09-14 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_home_facebook_home_instagram_home_linkdin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
    ]
