# Generated by Django 5.1.1 on 2024-09-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_rename_category_catagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
