# Generated by Django 5.1.1 on 2024-09-14 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_comment_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='pic',
        ),
    ]
